# Generated by Django 3.2.7 on 2021-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_auther', models.CharField(max_length=30)),
                ('book_description', models.TextField()),
                ('book_picture', models.ImageField(upload_to='')),
                ('book_publisher', models.CharField(max_length=30)),
                ('book_email', models.EmailField(max_length=254)),
                ('book_price', models.IntegerField()),
            ],
        ),
    ]
