# Generated by Django 3.2.7 on 2021-09-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='No desc', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.IntegerField(default=0),
        ),
    ]
